### ISSUE TITLE
Hey programatic API is a 404

### ISSUE THREAD

**Issue by roni-estein** [preset/preset#103]
Hey, this may not be an issue, I just installed this globally to use in a bash script. However, when attempting to run 'preset apply laravel:vite', I ran into an issue where is says there is a version mismatch. I couldn't find any documentation on the best way to either upgrade this or use it programatically.

![Screen Shot 2022-05-12 at 7 20 54 PM](https://user-images.githubusercontent.com/8517475/168187696-0272cb25-4218-47ef-aa3d-050da238ee8f.png)

**Comment by innocenzi** [comment]
Hey, I just need to update the Vite preset (and others) since I created a new major for Preset. But it doesn't change anything for you, don't worry. Thanks for the heads up!
