### ISSUE TITLE
@preset/cli exits with a 0 exit code on failure

### ISSUE THREAD

**Issue by jorupp** [preset/preset#110]
As part of setting up some presets for internal use on projects, I tried to set up a CI build that would make sure the presets could all be applied successfully.  However, the `preset` command doesn't appear to be setting a non-zero exit code when the preset fails to apply.  Is there a flag I need to set to cause a non-zero exit code if the preset fails to apply?

Version: `preset/0.7.0 linux-x64 node-v16.17.0`
Preset: `jorupp/simple-import-preset` (fails due to importing `editFiles` from `@preset/core`, which causes an issue per https://github.com/preset/preset/issues/106#issuecomment-1220802226)
Command: `preset apply jorupp/simple-import-preset && echo success`

Expected: "success" is not displayed
Actual: "success" is displayed

I expected https://github.com/preset/preset/blob/a7ea780c623a0b95d96725bea8d9f00c47251928/packages/cli/src/cli.ts#L77 to trigger an exit code of 1, but from my testing, that code doesn't get hit when the preset just fails to apply.  Additionally, doing it at the time `applyPreset` or `runMatchedCommand` return false appears it would be too early, as that's before the reporter has written the details.

**Comment by innocenzi** [comment]
Thanks! Should be fixed in https://github.com/preset/preset/commit/1dfe5f94b5549757d8982148c41e00ef56204e89.

**Comment by jorupp** [comment]
Thanks - that works once I force the `list` reporter via `env.CI=""`.  It results in a bunch of extra output lines as the spinner does its thing, but it's workable.  Though the debug reporter that applies by default in GitHub Actions (because env.CI is set) doesn't set the exit code.

**Comment by innocenzi** [comment]
Oh, that's an oversight. I'll add this to the debug reporter as well, sorry.

**Comment by innocenzi** [comment]
Should be fixed now, sorry about that!

**Comment by jorupp** [comment]
> Should be fixed now, sorry about that!

No worries - that works great now.  Thanks.
