### ISSUE TITLE
Prompt Action doesn't handle backspace

### ISSUE THREAD

**Issue by HexaCubist** [preset/preset#127]
At least from my testing, using the prompt action for plain text input doesn't allow the user to press backspace to delete input. Is this the current behaviour or have I misconfigured something?

**Comment by innocenzi** [comment]
It seems you are right, never noticed—this is indeed a bug

**Comment by innocenzi** [comment]
Just to let you know, I don't have a lot of bandwidth right now to investigate and fix, so PRs welcome 👍

**Comment by HexaCubist** [comment]
Thanks - I'll try and submit a PR next week for this and the other issue I filed if it seems like an easy fix!
