### ISSUE TITLE
SelectPromt Action doesn't handle `escape` & `ctrl +c`

### ISSUE THREAD

**Issue by jrson83** [preset/preset#129]
Using the SeelectPrompt action, it is not possible to exit the process using `escape` or `ctrl +c`.

**Comment by innocenzi** [comment]
Duplicate of #126, closing the previous one

**Comment by jrson83** [comment]
This issue is not a duplicate of #126. This one is related to SelectPrompt, while the other is related to TextPrompt.
So the issue at the moment still persists, but I will push another commit to fix #126.
