### ISSUE TITLE
How to use other repository instead of github

### ISSUE THREAD

**Issue by tyouzu1** [preset/preset#131]
https://github.com/preset/preset/blob/7aaba5483de652c4aaccfd9f014560f3a4df74dc/packages/core/src/resolve.ts#L70

like gitlab : `npx apply https://git.xxx.com/xxxx/aa/b`

**Comment by innocenzi** [comment]
This is not supported unfortunately. Open to PR adding that functionality, but I'd like to refactor our built-in system to use [`giget`](https://github.com/unjs/giget)
