### ISSUE TITLE
Yarn support

### ISSUE THREAD

**Issue by SirMishaa** [preset/preset#21]
Hello !

Does it also work with Yarn?

**Comment by innocenzi** [comment]
Hello, 

I am not sure which part of `use-preset` you are asking about, but the short answer is "yes". 

`use-preset` isn't tied to any package manager. If you decide to install it globally, you can do it with `npm i -g` or `yarn global add`, it doesn't matter as long as `use-preset` ends up in your `PATH`. 

If you're asking about the `installDependencies` context function, it will try to detect `yarn`, and if it doesn't find it, it will fall back to `npm`. 

If I couldn't answer your question, can you reopen and be more specific?
