### ISSUE TITLE
Does the package.json file get replaced when installing a preset 

### ISSUE THREAD

**Issue by SirMishaa** [preset/preset#22]
Does the package.json file get replaced when installing a preset ?

We should be able to add dependencies directly in the package.json file when adding a preset.

**Comment by innocenzi** [comment]
Hello, no, `package.json` isn't touched at all if the preset doesn't interact with it. `use-preset` doesn't rely on it for anything, you can actually use `npx use-preset <any-preset>` in an empty directory. It doesn't look for `package.json` files whatsoever. 

A preset can add dependencies to a `package.json` quite easily with the [`edit-json` action](https://docs.usepreset.dev/authoring/actions/edit-json). 

For instance, this preset will add a dependency on Tailwind CSS 1.2:

```js
module.exports = {
  actions: () => [
    {
      type: 'edit-json',
      file: 'package.json',
      merge: {
        devDependencies: {
          tailwindcss: '^1.2'
        }
      }
    }
  ]
}
``` 

If what a preset is actually doing isn't clear to you, feel free to reopen and ask for details.
