### ISSUE TITLE
Indent use tab or space

### ISSUE THREAD

**Issue by ycs77** [preset/preset#44]
Everyone’s code style is different. I'm using space indent in `package.json`.

Can add a new Method to set `editJson` indent to set `tab` / `2 space` / `4 space` ?

https://github.com/use-preset/use-preset/blob/374a1a5e13135b62162aa3a770a39f3e94e7f7f8/src/Handlers/EditJsonActionHandler.ts#L58-L60

**Comment by innocenzi** [comment]
Ah, good catch. I'll add a parameter to use a custom indentation style. Thanks!

**Comment by innocenzi** [comment]
This is implemented in the develop branch, it will be available in the next release. Thanks for the suggestion!
