### ISSUE TITLE
feat: edit dependencies action

### ISSUE THREAD

**Issue by innocenzi** [preset/preset#46]
New actions for ecosystem-specific dependency management. Currently, `edit-json` works fine for editing `package.json` and `composer.json` files, but it could help some syntactic sugar, and maybe new features (eg. sorting, see #45).

**Comment by ivorisoutdoors** [comment]
This sounds interesting. Please let me know if you want any help

**Comment by innocenzi** [comment]
Hey, thank you. I'm still thinking about the design of this one. What would the action contracts look like, with what properties. I think their names will be `edit-node-dependencies`, but I'm not exactly sure what the API should look like without being too redundant with the existing `edit-json` action. 

If you can give your thoughts about these interrogations, that would help me. 👍

**Comment by innocenzi** [comment]
This is implemented and will be available in `0.2`.
