### ISSUE TITLE
withoutAsking usage

### ISSUE THREAD

**Issue by skydiver** [preset/preset#50]
Hello @innocenzi 

To install node dependencies without confirmation i had to write my preset like this:

```
  .installDependencies()
    .for('node')
    .withoutAsking(false)
    .title('Install npm dependencies')
    .chain();
```

is the correct behavior? i was expecting to say `withoutAsking = true`

**Comment by innocenzi** [comment]
Hello, if you want the preset to **not** ask for confirmation, you can just not pass any variable to `withoutAsking`: 

```js
.installDependencies()
  .for('node')
  .withoutAsking()
  .title('Install npm dependencies')
  .chain();
```

The method accepts a variable in case you would like to couple it with a flag:

```js
// npx use-preset your-preset --no-interaction
.withoutAsking(({ flags }) => Boolean(flags.interaction))
```

The example above will install the dependencies without asking if `--no-interaction` is given. 

Does that answer your question?

**Comment by skydiver** [comment]
Thanks @innocenzi 

Yes, it answers my question.

What i found confusing are these lines from docs:

<kbd>![image](https://user-images.githubusercontent.com/578784/91379651-8d32a180-e7f9-11ea-8231-ecae9f7cbdbf.png)</kbd>

I've read: "by default `withoutAsking` uses a boolean true, so if i explicit add a true no confirmation is needed" and looks that whatever you're passing (a bool, a string) triggers the confirmation

Anyway, thank you for the help!

**Comment by innocenzi** [comment]
Oh, you're right, that is misleading. I'll try to clarify that right away. Thank you!
