### ISSUE TITLE
why double indentation in the edit API?

### ISSUE THREAD

**Issue by mattlehrer** [preset/preset#68]
I'm just reading about Preset and I really appreciate the philosophy. I've used Yeoman in the past and this makes much more sense to me.

I'd like to understand how you're thinking about indentation. If I'm understanding the documentation correctly, the options are either to double the previous line's indentation or to use a fixed indentation that isn't based on the previous line. I'd like to be able to add or subtract a single tab or number of spaces from the previous line. (Ideally, the library would detect tabs vs spaces if it's consistent in the file.)

**Comment by innocenzi** [comment]
Hey, that's a very valid request. To be sure I'm understanding right, you would like to increment or decrement the indentation level, right?

**EDIT**: actually after trying out, I remember - I can't detect the base indentation of the file easily, I just get the indentation of the *previous line*. If that line has 4 spaces, I can't really know that the base indentation is 2 spaces, so I can't add an `increment` and `decrement` option.

With Preset, I assume that we know about the file that we're editing so I thought it would not be an issue.

**Comment by mattlehrer** [comment]
Ok interesting. Thanks for looking into it. I thought about it more and I am not sure this is the right place to worry about it. Maybe it's something husky/lint-staged should take care of. Thank you.
