### ISSUE TITLE
Improve extract from template file to target file 

### ISSUE THREAD

**Issue by oanhnn** [preset/preset#69]
## Summary

When extract from template file to target file, it don't existed yet, preset make incorrect target path. 

## Steps to reproduce

Make preset with preset.ts

```ts
Preset.extract()
    .from('abc/.eslintignore')
    .to('.eslintignore')
    .withDots(true)
    .whenConflict(Preset.isInteractive() ? 'ask' : 'override')
```

Make template file `templates/abc/.eslintignore`

Run

```
mkdir ci-test
apply /path/to/preset ci-test
```

## Expect behavior?

The preset copy `templates/abc/.eslintignore` to `ci-test/.eslintignore`

## What is the current bug behavior?

The preset copy `templates/abc/.eslintignore` to `ci-test/.eslintignore/abc/.eslintignore`

Why not set `.to('')` ? Because it will make `ci-test/abc/.eslintignore`

**Comment by babichjacob** [comment]
Extract is always to a directory. You cannot extract to a file (path).

**Comment by oanhnn** [comment]
## Preset 

```ts
import { Preset } from "apply";

Preset.setName("oanhnn/test");
Preset.option('case', 1)

// 1. File to file
Preset.extract().from("foo/baz").to("baz").ifOptionEquals('case', 1);

// 2. File to dir
Preset.extract().from("foo/baz").to("bar").ifOptionEquals('case', 2);

// 3. File to not exist
Preset.extract().from("foo/baz").to("abc").ifOptionEquals('case', 3);

// 4. Dir to dir
Preset.extract().from("foo/bar").to("bar").ifOptionEquals('case', 4);

// 5. Dir to file
Preset.extract().from("foo/bar").to("baz").ifOptionEquals('case', 5);

// 6. Dir to not exist
Preset.extract().from("foo/bar").to("abc").ifOptionEquals('case', 6);
```

## Template directory

```
templates
└── foo
    ├── bar
    │   └── abc
    └── baz
```

## Target directory

```
ci-test
├── bar
│   └── xyz
└── baz
```

## Result

| Case | TemplatePath | TargetPath | Actual Target Path |
|-------|----------------|-------------|----------------------|
| 1 | File `foo/baz`  | File `baz`    | File `baz`                |
| 2 | File `foo/baz`  | Dir `bar`    | File `bar/foo/baz`   |
| 3 | File `foo/baz`  | Not existed | File `abc/foo/baz` |
| 4 | Dir `foo/bar`  | Dir `bar`    | File `bar/baz` |
| 5 | Dir `foo/bar`  | File `baz`  | Error | 
| 6 | Dir `foo/bar` | Not existed | File `abc/foo/bar/abc` |

## Expect

In case 3, file `abc` is created from copy of `foo/baz`.
If you want make file `abc/foo/baz` in case 3, please using `.from("foo").to("abc")` (case 4).

**Comment by innocenzi** [comment]
Not sure how to tackle this. It is not exactly a bug, it's the expected behavior. Changing this would be a breaking change. But your use case is not *that* specific so I'd like to support it as well. 

Do you have any suggestion? Maybe an option to not keep the input path's hierarchy?

Related: https://github.com/preset/cli/blob/main/src/Handlers/ExtractHandler.ts#L67

**Comment by oanhnn** [comment]
I'm sorry if that might be the behavior you would expect of the extract feature. To avoid breaking change, we should create a new action called `copy`. It have behavior like `cp` on Linux. 

```
Preset.copy(['foo/*.php', 'baz'])

Preset.copy(['foo/*.php', 'baz']).to('bar')

Preset.copy().from(['foo/*.php', 'bar']).to('bar')
```

In case extract file to *existed file* ( case 1 in https://github.com/preset/cli/issues/69#issuecomment-800854214 ) will be recommend to using `copy` feature. 😄

**Comment by innocenzi** [comment]
Um, `copy` is an action that I thought of already, and that would be similar to `delete` in scope. It would only copy files in the target directory.

What do you think of a new `withoutHierarchy` parameter? 

```ts
Preset.extract()
  .from('abc/.eslintignore')
  .withDots()
  .withoutHierarchy() // new parameter
```

Not sure of the name, but the idea would be that instead of deep-copying `abc/.eslintignore`, only `.eslintignore` (without its parent folder) would be copied. That would mean that `.to()` is not necessary.

**Comment by oanhnn** [comment]
Good idea.
You need define behaviors in all case:
- Template Path is File / Dir / Glob
- Target Path is File / Dir / Not existed yet
- With / without `hierarchy` parameters
