### ISSUE TITLE
When trying to publish:vendor by execute, nothing happens

### ISSUE THREAD

**Issue by bebetoalves** [preset/preset#76]
Hello, I'm trying to make a preset for Laravel that will publish the vendor.

After installing the desired package, I try execute:

```js
Preset.execute('php')
    .withArguments([
        'artisan',
        'vendor:publish',
        '--provider="NunoMaduro\\PhpInsights\\Application\\Adapters\\Laravel\\InsightsServiceProvider"',
    ])
```

However, the vendor is not published, and there are no errors.

**Comment by innocenzi** [comment]
Hey, are your vendors published if you perform the command manually? I tried to use an artisan command with `execute` and it worked as expected. 

![](https://i.imgur.com/Fto5mbv.png)

Maybe the package is not yet installed when you use `execute`?

**Comment by bebetoalves** [comment]
> Hey, are your vendors published if you perform the command manually? I tried to use an artisan command with `execute` and it worked as expected.
> 
> ![](https://camo.githubusercontent.com/0ad5d1ffc783369874db0c28dbd07e42ecbe2c252e1b657f30b57c4ad93c33dc/68747470733a2f2f692e696d6775722e636f6d2f46746f356d62762e706e67)
> 
> Maybe the package is not yet installed when you use `execute`?

Yes, I can run the command manually. And yes, I'm sure the package is installed before the `execute()` is run.

```js
// Install PHP Insights.
Preset.group((preset) => {
    preset.execute('composer')
        .withArguments([
            'require',
            'nunomaduro/phpinsights:dev-master',
            '--dev',
            '--no-interaction'
        ])
    
    preset.execute('php')
        .withArguments([
            'artisan',
            'vendor:publish',
            '--provider="NunoMaduro\\PhpInsights\\Application\\Adapters\\Laravel\\InsightsServiceProvider"',
        ])
    
    preset.editPhpPackages()
        .set('scripts', { 'lint': '@php artisan insights --no-interaction --min-quality=80 --min-complexity=90 --min-architecture=75 --min-style=95' });
})
    .withTitle(`🚀 Installing PHP Insights...`)
    .ifOption('insights')
```

**Comment by innocenzi** [comment]
This will most likely no longer be an issue in the next major because of the rewrite.
