### ISSUE TITLE
feat: guess the name of the repository with prefix `preset-`

### ISSUE THREAD

**Issue by ycs77** [preset/preset#78]
If I create the repository call `user/preset-a`, I hope will use `apply user/a` or `apply user/preset-a` both can to run the preset..

I think this feature will allow me to create repo with `preset-` without having to type the prefix `preset-`.

Is this feature possible?

**Comment by innocenzi** [comment]
Does the [alias feature](https://preset.dev/docs/concepts/aliases/#aliases) solve your need? While this is technically possible, I'd rather avoid such conventions. There is also the possibility to organize presets in a [monorepository](https://preset.dev/docs/guides/hosting/#mono-repositories).
