### ISSUE TITLE
How does Multiselect ArrayType work?

### ISSUE THREAD

**Issue by braebo** [preset/preset#83]
I've been struggling to figure out how to implement the [MultiSelect Prompt](https://github.com/enquirer/enquirer#multiselect-prompt).

![Screenshot 2021-06-21 at 5 59 12 PM](https://user-images.githubusercontent.com/55504972/122833397-e739b180-d2ba-11eb-90b6-813b0c65593c.png)

<details>
<summary>code</summary>

```ts
import { Preset } from 'apply';

Preset.setName('Config');
Preset.prompt()
	.add('configs', {
		type: 'ArrayPrompt',
		name: 'configs',
		message: 'What configs would you like?',
		choices: ['stylelint', 'settings.json']
	});
```

</details>

I've read through the docs multiple times, but can't seem to understand how it's meant to work.

Any advice would be greatly appreciated!

**Comment by innocenzi** [comment]
Hey, in your case, just change `ArrayPrompt` by `multiselect`. That's the only change needed I think. :)

![](https://i.imgur.com/GK6f3lI.png)

**Comment by braebo** [comment]
Awesome, thanks!  Loving Preset, thank you for such a great project!!
