### ISSUE TITLE
Can't seem to be able to catch errors.

### ISSUE THREAD

**Issue by braebo** [preset/preset#84]
I'm not sure how catching errors is supposed to work.  `editJson` errors on JSONC (JSON with comments), which is common  in files like `tsconfig`, or `settings.json`.

Is there a recommended way to handle errors and provide error messages?

**Comment by innocenzi** [comment]
Hmm not really unfortunately. I hadn't that feature in mind when designing it.

I'll keep the issue open so hopefully I can improve this later.

**Comment by innocenzi** [comment]
With the new reporters and the new use of `debug`, this won't be an issue anymore (hopefully!).

![](https://i.imgur.com/AKUF8xj.png)

![](https://i.imgur.com/iJpxFW4.png)
