### ISSUE TITLE
Preset.editJson().merge() produces duplicated code when you add values within an array

### ISSUE THREAD

**Issue by bastiW** [preset/preset#87]
Le'ts say I want to edit the package.json and and want to configure jest. Then I have the following code:

```
  Preset.editJson('package.json').merge({
    jest: {
      roots: ['<rootDir>/src'],
      setupFilesAfterEnv: ['<rootDir>/jest/jest.setup.js'],
      collectCoverageFrom: ['src/**/*.{js,jsx,ts,tsx}', '!src/**/*.d.ts'],
      testMatch: ['<rootDir>/src/**/__tests__/**/*.{js,jsx,ts,tsx}', '<rootDir>/src/**/*.{spec,test}.{js,jsx,ts,tsx}'],
      testEnvironment: 'jsdom',
      transform: {
        '^.+\\.(js|jsx|mjs|cjs|ts|tsx)$': '<rootDir>/node_modules/babel-jest',
        '.+\\.(svg|css|styl|less|sass|scss|png|jpg|ttf|woff|woff2)$': 'jest-transform-stub',
      },
      transformIgnorePatterns: ['[/\\\\]node_modules[/\\\\].+\\.(js|jsx|mjs|cjs|ts|tsx)$', '^.+\\.module\\.(css|sass|scss)$'],
      moduleNameMapper: {
        '^.+\\.module\\.(css|sass|scss)$': 'identity-obj-proxy',
      },
      watchPlugins: ['jest-watch-typeahead/filename', 'jest-watch-typeahead/testname'],
      resetMocks: true,
    },
  });
```

I run my preset once: everything as expected. 
I run it several times. Then there are two cases:

1. ✅ Code is automatically merged and not duplicated. 
For example the ` "testEnvironment": "jsdom",`  or the `    "resetMocks": true`:  this will not be added again to the package json
2. ❌  Code like the 
```
      roots: ['<rootDir>/src'],
```
```
      watchPlugins: ['jest-watch-typeahead/filename', 'jest-watch-typeahead/testname'],
```
This will be added several times to the package json

**Conclusion**: 
It looks like that his happens with array values only. 
I would expect that that also checked and not added again when they are already existing.

**Comment by innocenzi** [comment]
Hey, presets are expected to be ran only once. You can probably [add a condition](https://preset.dev/docs/api/action/#methods) to your `editJson` action to check if it should be performed, if you need such a check. 

Regarding the merge issue, it is done with the package [`deepmerge`](https://github.com/TehShrike/deepmerge), without anything custom. So, maybe an issue on their side?

**Comment by innocenzi** [comment]
Feel free to re-open if needed. 👍

**Comment by bastiW** [comment]
looks like that deepmerge has an [option to combine array values](https://github.com/TehShrike/deepmerge#arraymerge-example-combine-arrays) 

I created a pull request to fix this
https://github.com/preset/cli/pull/90
