### ISSUE TITLE
Init new preset without git to use it as a local code generator

### ISSUE THREAD

**Issue by bastiW** [preset/preset#88]
I would like to have an option to create an preset without git. This would make it possible to use the code generator for local code generation. This I could use for example when I want to generate a new menu entry and a page. This I don't want to have in a separate repository. It should just live in my project. 

I would suggest to have an optional argument to the init command

`npx apply <preset-name> --init --local `

or even have the git as an optional command:

`npx apply <preset-name> --init --add-git`

**Comment by innocenzi** [comment]
I added the `--no-git` flag that should skip the creation of a repository. Let me know if it doesn't work as expected. :)

**Comment by bastiW** [comment]
Thanks! I also think we can remove the templates/.gitignore file, as I don't want to have this copied over into my local project again.

**Comment by bastiW** [comment]
Documented it here
https://github.com/preset/website/pull/12/files
