### ISSUE TITLE
Nested Preset

### ISSUE THREAD

**Issue by jrrmcalcio** [preset/preset#98]
Hello I'm trying to create a preset and I'm testing it locally so when I run it I use the command:

``
preset apply ../preset
``

The onlything I have on that preset is:

```
export default definePreset({
  name: 'jetstream',
  options: {
    base: true,
    tailwindcss: true,
    pest: true,
    https: false,
  },
  handler: async (context) => {
     await applyNestedPreset({
      title: 'install Vite',
      preset: 'laravel-presets/vite',
      inheritsArguments: true,
    });
  },
});
```

The nested preset did not execute:

```
C:\laragon\www\testpreset (main)
λ preset apply ../preset

  ERR  Failed applying: laravel:jetstream.

  ×  Failed action: install Vite
  Presets  1 failed (1)
  Actions  0 ran | 1 failed (1)
     Time  1.02s


  ERR_PRESET_FAILED  Preset failed because some of its actions failed.
```

Can you please help me understand why it's falling?  I tried to read the Preset code but I don't know what is going on :(

**Comment by innocenzi** [comment]
Hey! Using `--debug` might give you clues on what's happening behind the scenes and why it's failing.

**Comment by jrrmcalcio** [comment]
Ok, the problem was the files on my temp folder were missing (cache).  

I'm on windows so I went to ```%USERPROFILE%\AppData\Local\Temp\preset``` and remove all files there, run it again and it went through :) thank you very much for your help man.
